name: Laravel CI/CD

on: workflow_dispatch

jobs:
  workflow-dispatch-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls -al
