name: Laravel CI/CD

on: [push]

jobs:
  notification-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.1.1
        env:
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        with:
          author_name: "Action"
          fields: repo, message, commit, author, action, eventName
